### PR TITLE
add set ball position service

### PR DESCRIPTION
**Pull request by SammyRamone**
## Proposed changes
Adds a new service to set ball position in simulation. Also changes set robot position to set robot pose

## Necessary checks
- [ ] Update package version
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [x] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

### CODE REVIEW

**Review by lilioid — CHANGES_REQUESTED** [review]
Since the msgs define the type of data transmitted and their semantic meaning is added when used on a specific topic, I would prefer to see something like a `SetObjectPosition.srv` and a `SetObjectPose.srv`.

**Comment by SammyRamone** [comment]
> Since the msgs define the type of data transmitted and their semantic meaning is added when used on a specific topic, I would prefer to see something like a `SetObjectPosition.srv` and a `SetObjectPose.srv`.

**Comment by SammyRamone** [comment]
> Since the msgs define the type of data transmitted and their semantic meaning is added when used on a specific topic, I would prefer to see something like a `SetObjectPosition.srv` and a `SetObjectPose.srv`.

done

**Review by lilioid — DISMISSED** [review]
The two services are still slightly inconsistent because `SetObjectPose.srv` requires a `robot_name` attribute which is weirdly named robot and not object and because `SetObjectPosition` does not have such an attribute.
But since it is only really used by us, I think it is fine :shrug:

**Comment by SammyRamone** [comment]
> The two services are still slightly inconsistent because `SetObjectPose.srv` requires a `robot_name` attribute which is weirdly named robot and not object and because `SetObjectPosition` does not have such an attribute.
> But since it is only really used by us, I think it is fine shrug

I fixed it anyway

**Review by lilioid — APPROVED** [review]

**Pull request merged**
