### PR TITLE
Dynamic colorspace

### PR DESCRIPTION
**Pull request by jaagut**
These changes are adding two new message-types that are needed for the dynamic color-space node to publish color-spaces and to get config from the vision-node.

### CODE REVIEW

**Review by NFiedler — CHANGES_REQUESTED** [review]
Please rename the messages by removing "Message" at the end of their name. None of the other messages have that.
And shouldn't uint8 be the optimal type in the colorSpace message? Why are 32 bit needed to encode 8-bit color values?

**Comment by Flova** [comment]
> And shouldn't uint8 be the optimal type in the colorSpace message? Why are 32 bit needed to encode 8-bit color values?

We discussed this a while ago. The first implementation used unit8 to encode the colors. Counterintuitively this was much slower (like 400ms for encoding a single message), because python does some weird internal processing with unit8 message arrays. Finally we decided to accept the size overhead to get a performance boost.

**Comment by NFiedler** [comment]
In an overall perspective, this is really scary, but here it is a great reason... Please add a comment in the message while I'm falling into a crisis about reality...

**Comment by SammyRamone** [comment]
Please remove the "Message" as @NFiedler sugested. Otherwise it looks fine
Regarding the uint8 issue: This seems strange but is possible that python just does something weird here

**Review by SammyRamone — APPROVED** [review]

**Review by Flova — APPROVED** [review]

**Pull request merged**
