### PR TITLE
add LookAt.action

### PR DESCRIPTION
**Pull request by val-ba**
## Proposed changes

Add LookAt action for head behavior
## Necessary checks
- [ ] Update package version
- [x] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Put the PR on our Project board

### CODE REVIEW

**Review by Flova — APPROVED** [review]

**Comment by timonegk** [comment]
It might also make sense to add a distance field to the feedback to get the angular distance from the goal.

**Comment by Flova** [comment]
> It might also make sense to add a distance field to the feedback to get the angular distance from the goal.

Good idea. I also imagine the percentage as the angular distance left dividend by the angular distance at the beginning of the action (times 100), so it should be very easy to include.

**Comment by val-ba** [comment]
> > It might also make sense to add a distance field to the feedback to get the angular distance from the goal.
> 
> Good idea. I also imagine the percentage as the angular distance left dividend by the angular distance at the beginning of the action (times 100), so it should be very easy to include.

would it be better to have a percentage or absolute value?

**Comment by Flova** [comment]
I would just include both

**Comment by val-ba** [comment]
> It might also make sense to add a distance field to the feedback to get the angular distance from the goal.
Do you mean degree or radians by angular distance? We would need the pan and tilt distance seperately, wouldnt we?

**Review by Flova — APPROVED** [review]

**Pull request merged**
